from .deploy_linear import remove_fakequantize_and_collect_params
from .deploy_tpu import remove_fakequantize_and_collect_params_tpu
from .deploy_float import remove_fakequantize_and_collect_params_flt
from .deploy_transformer import remove_fakequantize_and_collect_params_tf
#from .deploy_academicnlp import remove_fakequantize_and_collect_params_academic
